apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: crud-api
  name: crud-api
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IubGFiLmludCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJIYXJib3IxMjM0NSIsImF1dGgiOiJZV1J0YVc0NlNHRnlZbTl5TVRJek5EVT0ifX19
kind: Secret
metadata:
  name: harbor-registry
  namespace: crud-api
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQwakNDQXJxZ0F3SUJBZ0lVZmlqdkhTbkRISzArM0F3OFU4WGx4Qm1HV2tJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1BqRWJNQmtHQTFVRUF3d1NZM0oxWkMxMWMyVnljeTVzWVdJdWFXNTBNUXN3Q1FZRFZRUUdFd0pDVWpFUwpNQkFHQTFVRUJ3d0pVMkZ2SUZCaGRXeHZNQjRYRFRJeU1URXlNakE1TWpZek5Gb1hEVEl6TVRFeU1qQTVNall6Ck5Gb3dnWXd4Q3pBSkJnTlZCQVlUQWtKU01SSXdFQVlEVlFRSURBbFRZVzhnVUdGMWJHOHhIVEFiQmdOVkJBY00KRkZOaGJ5QkNaWEp1WVdSdklHUnZJRU5oYlhCdk1SUXdFZ1lEVlFRS0RBdE1ZV0p2Y21GMGIzSnBiekVYTUJVRwpBMVVFQ3d3T1RHRmliM0poZEdsdmJpQkVaWFl4R3pBWkJnTlZCQU1NRW1OeWRXUXRkWE5sY25NdWJHRmlMbWx1CmREQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQVBsSXBYQmtVUTVxQ1ZSRHNSUGQKaG1WVXMvdFpVTUUrOUY2amxZQ0FUOGtCQXVCSWhBZGlGSnRxSWoveGVzTXUxb3BTSnBFV1RtK3NFOENtZVZJWQphSlZsRC9ZRWlzSm52MXJ3WE5UaVZ5UzBwcFdSUGZpa1E1RmJScERrVFhOdzRPYWxpUXFhMXpaY3llRm5HNmtZCitIR2tuY3hJTWFhZnRvRnpqT3Y5bjdDVkc2enp1WEo5V3FNeHVpR2tETTFOR0J0Tmk4cmJqSGVvb0pKeDlPMFIKcWFoaWpLVkdiYU5yZ0dkUkdoMHVVbDBOZnlZZDB2d0kwRnVtZUlzS1RJajJyeXAxZExCSDZTc2FKSldmZ3BnWApTR3ovQ0JBbk9SdFA3VFpHdW8yRGJIQzltR2FTcVhWZVNCdEkyZTZadmhWQm5YdndCakNPQ0ZsaDVVNHUxTFFsCkJoY0NBd0VBQWFONU1IY3dId1lEVlIwakJCZ3dGb0FVRjdCZ28xSk1zSGg4T3FHVmIyeCtIOFViUWprd0NRWUQKVlIwVEJBSXdBREFMQmdOVkhROEVCQU1DQlBBd0hRWURWUjBSQkJZd0ZJSVNZM0oxWkMxMWMyVnljeTVzWVdJdQphVzUwTUIwR0ExVWREZ1FXQkJSay9QWklPYkRCQnY1K1Y1NSt5YnB0TFJINEZ6QU5CZ2txaGtpRzl3MEJBUXNGCkFBT0NBUUVBVlhLcit0S0VLZGo3cmtrWHVOaHhVdmlSc3AxUlJuVDFLbzZDWjl3MFlyZHlscXJUYjEzMjRSVWYKRXQ5VTlwbXhIaFBlSm9SRGxua0RiU0JTZUZRbm1BbDZlQ0dYQVJNa09VSWdLdFRpeVA0ckZRWEpmOHVDaUtlMQpzK2RWQklHSk1BcllpU3VLNGRJVm9lZnlMRzl3ZmdnZTRZR0xsTkdyYzRaRTBsWXkwKzg5TFRZcEtZRTkwd1B3CjNxY3B3Z2EvZnJ5K1BjR3EvZUFmRkgvNFBnNzlUa1ExTDFTSElmYVcrdmQ1YSt5aXVLS25OVnZxWEZuMlR6V1QKcXNObHplOGF2cmpwamxqVE1vUHl0bXJVcnhIZXBTNDIyMGdscmtGcExKY1FrZFNyRWlFL2IrV0U0WS8veW5QUQpBMEhPZ0t4clZrSmRGWDRWRUtOczBWbmFOb090L1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRDVTS1Z3WkZFT2FnbFUKUTdFVDNZWmxWTFA3V1ZEQlB2UmVvNVdBZ0UvSkFRTGdTSVFIWWhTYmFpSS84WHJETHRhS1VpYVJGazV2ckJQQQpwbmxTR0dpVlpRLzJCSXJDWjc5YThGelU0bGNrdEthVmtUMzRwRU9SVzBhUTVFMXpjT0RtcFlrS210YzJYTW5oClp4dXBHUGh4cEozTVNER21uN2FCYzR6ci9aK3dsUnVzODdseWZWcWpNYm9ocEF6TlRSZ2JUWXZLMjR4M3FLQ1MKY2ZUdEVhbW9Zb3lsUm0yamE0Qm5VUm9kTGxKZERYOG1IZEw4Q05CYnBuaUxDa3lJOXE4cWRYU3dSK2tyR2lTVgpuNEtZRjBocy93Z1FKemtiVCswMlJycU5nMnh3dlpobWtxbDFYa2diU05udW1iNFZRWjE3OEFZd2pnaFpZZVZPCkx0UzBKUVlYQWdNQkFBRUNnZ0VBTGROQWNtWkdqa2RJMnNBczI3R0Q1TG5LOGtBcmU3TEdlbVZJOU52aGp0cE0KUEkyb0U3RmdoMmRkejNKbE5sODBXaTRhMzk0QllqNzRUSmh0d2YweHNKRG8rN2svQnRqS2tQMlJteUxXa1MxUwpXRGxnY29aRDA0TTdlQ1EzNXFwUDlhWmxpRmtKaWZsSnRWRmVnTm5SeGhaVVdickZ3ZE1uV2ltek5LaWxnL0N3ClNtQ2dRV0Z5WVdURjRNWWJocGFEYm01VUZRRUgwNm4yNkJ0SGFkdnl4WFpUSGVhd2NXVnFnYkdwU0hhYnF6aUIKSSs5bjNwNWQva1pBdGV3bHYvQklKM1RaR3NpZmxLRG5ORDZEcC8zaDF3K0loTVpzbWdYbzMwaXVNdmpGeWpYaQpIMzJPMHd0TVRmUkg5NmRuWEdnaEhSL2hWcEFDSi9mQmd3UmZpc090QVFLQmdRRDlDWWVmc1k3Wk4wcFQ3bWEvCnMvYW4zZ0orV3pWUnA5UUV1RlhIcXFzakVBSm1JZW1SYTI3MUZUOTZhUFhaelBXeURjdk5rT2VxNXlKc2lzdEwKeWc5N2lSSFNrbm5oWHY0L2o1TVlXWDN1U3U0ZHVLaGpDeXlWRFVMcVpqRVF5dGtNYThtUlRCdDU1K05uTFBKeApYRk9UNE0yNW1udnRpTVA5SmNQeFltMTVBUUtCZ1FEOE05Mlp1aGlDZk1NTDhXNVJGdlQzeEtVcmozcHdUWGlRCitJdXVnVHpFclQyRE5VUHRkZXVjVkFma1ptczdoekpOU0Q4OXNrOHc1UlFObkxlL2VoWThJQU5rN1M2R3E4b0wKMGxMQWh1Q2dJOHp5dFJsNEtmSHJ3TkYybzFVd2NDWlpPb0lTb2x1UVpGMEEzS3kxRWhvMjF4YTYwVmxEaEs5QgozY1YrVHVBbkZ3S0JnUURIWVpMMFNqeDgvQXdkUm1TLytWWUp2KzNIRXFkWXlCMVArcy9jbktaczRsaUJrWWN4CmhxM1BnQWFjdGNmQzdyVktyNFEvWGthdGE2SzhWRUVNWHhNRURHVjJ2dVE2cVZjOVRpeGhxMktIT1pPVzU4SUgKQ084QUk0cnVsOGRocS9TS3pRUHU4VUZWTlZzQ0dYQ1AwbWdveGFKVTlWMWhOYnI0NWFFWHVxNzRBUUtCZ0RWZQpGRXB2WXJoYUJqd0V2cjlTQ0V4VnhFM1BjcTFJOTNaVjRkanZhQmlHUURuL2ozdzBNOE5FMU5hMEJZVDNPdUczCnBBbytMUnUvbmRxeml2NXRxejdWMTJJSC9veG8xYnhpcVRnc1VtUVFyMUc4bU1NZ3ZSeVNGTUR5RnhqRTRwaUgKRlBjMGZBTzErU2d4aWlwV3hrMU1mbmJSemYzSG1mNXFHMXg2L0Z2SkFvR0JBTTh6Lyt5K2dBSjh2RElvb0Q4ZQpISE5YQzlZTnNWaEE4T2N4bUFia3lhWWNNSno1K09COFE3anhUaFZScWtmSU82bDNpa3Y2dTBWclhRUjlYS1FDCmI2V2FXRW9RSTlIZU5Na25XcjVva09vQm5VKzVyYldLaXZhZjFmTzZBQnNueDFnMDFNOHVscjdqd0RlU0RzVkUKd2FlQjBYOU9zaVdDVEh0QnJHN1g5OG9zCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: crud-api-tls
  namespace: crud-api
type: kubernetes.io/tls
---
apiVersion: v1
kind: Secret
metadata:
  name: crud-database-creds
  namespace: crud-api
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql.database.svc.cluster.local:5432/postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "36FMYk3CMU"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-api-deployment
  namespace: crud-api
  labels:
    app: crud-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-api-app
  template:
    metadata:
      labels:
        app: crud-api-app
    spec:
      containers:
        - name: crud-api
          image: harbor.lab.int/crud-users/crud-users-api:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: crud-database-creds
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: crud-database-creds
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crud-database-creds
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                secretKeyRef:
                  name: crud-database-creds
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
      imagePullSecrets:
      - name: harbor-registry            
---
apiVersion: v1
kind: Service
metadata:
  name: crud-api-service
  namespace: crud-api
spec:
  selector:
    app: crud-api-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crud-api-ingress
  namespace: crud-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "crud-api.lab.int"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crud-api-service
                port:
                  number: 8080
  ingressClassName: nginx
