apiVersion: v1
kind: Secret
metadata:
  name: crud-database-creds
  namespace: crud-users
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "kz1Ix8YYc8"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"