apiVersion: v1
kind: Secret
metadata:
  name: crud-database-creds
  namespace: crud-users
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql.database.svc.cluster.local:5432/postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "36FMYk3CMU"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
