name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Checkout action tools repo
      uses: actions/checkout@v3
      with:
        repository: DevOps-Flow/actions
        path: ./actionTools
    - name: Maven Build
      uses: ./actionsTools/build
      with:
        settings: ${{ secrets.MAVEN_SETTINGS }}
